---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod1
  labels:
    app: demo1
spec:
  containers:
  - name: demo-container1
    image: centos:latest
    command: ['sh', '-c', 'echo Hello World! && sleep 300']

